name: CI

on: push

jobs:
  buid:
    runs-on: 'ubuntu-20.04'

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-versions: '8.1'
            drupal-versions: 'stable'

          - php-versions: '8.2'
            drupal-versions: 'stable'

          - php-versions: '8.1'
            drupal-versions: '9.5'
            drupal-project-hash: '9.x'

          - php-versions: '8.2'
            drupal-versions: '9.5'
            drupal-project-hash: '9.x'

          - php-versions: '8.2'
            drupal-version: '10@beta'

    env:
      DRUPAL_VERSION: ${{ matrix.drupal-versions }}
      DRUPAL_PROJECT_SHA: ${{ matrix.drupal-project-hash }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Test
        run: echo "$DRUPAL_PROJECT_SHA $DRUPAL_VERSION. Today is $DAY_OF_WEEK!"
