name: Deploy

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  deploy:
    runs-on: 'ubuntu-20.04'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
