name: Deploy

on:
  push:
    branches:
      - '^[0-9]+.[0-9]+.x$|^[0-9]+.x(?:\-[0-9]+\.x)?$|^ci.*'
    tags:
      - '*'
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  deploy:
    runs-on: 'ubuntu-20.04'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
